# Site settings
title: Ace Racing
url: https://www.aceracing.org

# File layout
css_path: /assets/css
js_path: /assets/js
img_generic_path: /assets/img/generic
video_path: /assets/vid
icon_path: /assets/icons

# Colour settings
colour:
  dark:  '#160f11'
  light: '#f8f4ff'
  red:   '#c00000'

# Build settings
markdown: kramdown
permalink: pretty
